// <auto-generated />
using System;
using API_dot.net.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_dot.net.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231006100909_SeedVillaTablesWithCreatedDate")]
    partial class SeedVillaTablesWithCreatedDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_dot.net.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Squares")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Сapacity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 10, 6, 17, 9, 9, 116, DateTimeKind.Local).AddTicks(7869),
                            ImageUrl = "https://unsplash.com/photos/2pPw5Glro5I",
                            Name = "Royall Villa",
                            Squares = 100,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Сapacity = 40
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 10, 6, 17, 9, 9, 116, DateTimeKind.Local).AddTicks(7878),
                            ImageUrl = "https://unsplash.com/photos/2pPw5Glro5I",
                            Name = "Medium Villa",
                            Squares = 70,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Сapacity = 25
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 10, 6, 17, 9, 9, 116, DateTimeKind.Local).AddTicks(7878),
                            ImageUrl = "https://unsplash.com/photos/2pPw5Glro5I",
                            Name = "Low Villa",
                            Squares = 40,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Сapacity = 10
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
